### ISSUE TITLE
認証情報設定ファイルを追加

### ISSUE THREAD

**Issue by naogify** [geolonia/tile-sentinel2#11]
`username` と `password` が直書きなので、設定ファイルに切り出しする。

**Comment by keichan34** [comment]
他のプロジェクトと一貫性を持つために envrc を使いましょう 👍

**Comment by naogify** [comment]
ドキュメントで、`.netrc` を使っていたので、こちらを使おうと思います…!

https://sentinelsat.readthedocs.io/en/stable/api_overview.html#authentication


`.envrc` を使えれば良いなと思って以下の形式で試してみたのですが、`sentinelsat.exceptions.UnauthorizedError: Invalid user name or password` エラーでダメでした。

```
machine="apihub.copernicus.eu"
login="your username"
password="your password"
```
